### ISSUE TITLE
Error: Braintree API Client Misconfigured: the clientApiUrl provided in the clientToken is invalid

### ISSUE THREAD

**Issue by JDevjs** [stevensgarcia/meanshop#1]
i get this error when im in the checkout page and the payment options form is **not showing** below the ngcart (`<braintree-dropin options="paymentOptions">loading..</braintree-dropin>`) please help i wasted so much time on this...

`Error: Braintree API Client Misconfigured: the clientApiUrl provided in the clientToken is invalid`

**Comment by stevensgarcia** [comment]
Hi, I did this as a personal project long time ago. I don't provide support for it. You should figure it out by your self.
